url: https://rrafols.github.io/
baseurl: ""
name: Development mumbo jumbo
description: ""

theme: jekyll-theme-tactile

highlighter: rouge
markdown: kramdown
kramdown: 
  input: GFM
  hard_wrap: false